apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2 # Kubernetes: Demonstrate scalability
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36.1 # Small, basic image
        command: ['sh', '-c', 'until nc -z user-postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: user-service
        image: anguloaguilars/user-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: SECRET_KEY
          value: "sandra1212"
        # Connect to the PostgreSQL service using its K8s DNS name
        - name: DATABASE_URL
          value: "postgresql://sandra47:sandra1212@user-postgres-service:5432/usersdb"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP # Internal service
