apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-mongo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Storage System: Using K8s volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-mongo-deployment
spec:
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
      - name: catalog-mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: catalog-db-storage
          mountPath: /data/db
      volumes:
      - name: catalog-db-storage
        persistentVolumeClaim:
          claimName: catalog-mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo-service
spec:
  selector:
    app: catalog-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
