apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Storage System: Using K8s volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres-deployment
spec:
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: user-postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sandra47"
        - name: POSTGRES_PASSWORD
          value: "sandra1212"
        - name: POSTGRES_DB
          value: "usersdb"
        volumeMounts:
        - name: user-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: user-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres-service
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
